# Generated by Django 2.2.4 on 2019-10-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.FilePathField(default=-1, path='Projects/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.FilePathField(default=-1, path='Projects/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.FilePathField(default=-1, path='Projects/img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image5',
            field=models.FilePathField(default=-1, path='Projects/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='Projects/img'),
        ),
    ]
